import PDFDocument from 'pdfkit'

export function generateShotListPDF(project, analysis) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 })
    const chunks = []
    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    // Title
    doc.fontSize(20).font('Helvetica-Bold').text(project.name || 'Untitled Project', { align: 'center' })
    doc.fontSize(12).font('Helvetica').text('Shot List — Generated by CineAssist AI', { align: 'center' })
    doc.moveDown(2)

    if (!analysis?.scenes?.length) {
      doc.text('No scenes available.')
      doc.end()
      return
    }

    for (const scene of analysis.scenes) {
      doc.fontSize(14).font('Helvetica-Bold')
        .text(`Scene ${scene.number}: ${scene.title}`)
      doc.fontSize(10).font('Helvetica')
        .text(`Mood: ${scene.mood} | Style: ${scene.style} | Duration: ${scene.duration}`)
      doc.moveDown(0.5)

      if (scene.shots?.length) {
        for (let i = 0; i < scene.shots.length; i++) {
          const shot = scene.shots[i]
          doc.fontSize(10).font('Helvetica-Bold')
            .text(`  Shot ${i + 1}: ${shot.type} — ${shot.description}`)
          doc.fontSize(9).font('Helvetica')
            .text(`    Lens: ${shot.lens} | Movement: ${shot.movement} | Angle: ${shot.angle}`)
            .text(`    Lighting: ${shot.lighting}`)
            .text(`    Duration: ${shot.duration} | Intent: ${shot.intent} | Confidence: ${shot.confidence}%`)
          doc.moveDown(0.3)
        }
      }
      doc.moveDown(1)

      if (doc.y > 700) doc.addPage()
    }

    doc.end()
  })
}

export function generateCSV(analysis) {
  if (!analysis?.scenes?.length) return 'No data'

  const headers = ['Scene', 'Shot', 'Type', 'Description', 'Lens', 'Movement', 'Angle', 'Lighting', 'Duration', 'Status', 'Confidence', 'Intent']
  const rows = [headers.join(',')]

  for (const scene of analysis.scenes) {
    if (!scene.shots?.length) continue
    for (let i = 0; i < scene.shots.length; i++) {
      const s = scene.shots[i]
      const row = [
        `"Scene ${scene.number}: ${scene.title}"`,
        i + 1,
        s.type,
        `"${(s.description || '').replace(/"/g, '""')}"`,
        s.lens,
        s.movement,
        s.angle,
        `"${(s.lighting || '').replace(/"/g, '""')}"`,
        s.duration,
        s.status,
        s.confidence,
        s.intent,
      ]
      rows.push(row.join(','))
    }
  }

  return rows.join('\n')
}
